"""Emit the generated files: one Chelis data module per calendar, the package's
provenance module, and a plain-text listing of everything each parse produced.
Chelis output is already in `chelis fmt` canonical form."""

from __future__ import annotations

import datetime
import itertools
import re

from tides_sync.model import Published, Source
from tides_sync.snapshot import Snapshot

HEADER = "-- Generated by the tides sync generator from its pinned upstream snapshot. Do not edit; regenerate."


def pascal(key: str) -> str:
    return "".join(part.capitalize() for part in key.split("_"))


def string_literal(text: str) -> str:
    if not re.fullmatch(r"[ -~]*", text):
        raise ValueError(f"non-ASCII or control character in {text!r}")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def date_literal(day: datetime.date) -> str:
    return f"date({day.year}i64, {day.month}i64, {day.day}i64)"


def comment_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def retrieved(snaps: dict[str, Snapshot]) -> datetime.date:
    """A calendar's retrieval date: that of its oldest document."""
    return min(s.retrieved for s in snaps.values())


def published_module(source: Source, snaps: dict[str, Snapshot], published: Published) -> str:
    key = source.key
    ordered = [snaps[part.name] for part in source.parts]
    names = [
        f"{key}_published_holidays",
        f"{key}_published_from",
        f"{key}_published_until",
        f"{key}_published_source",
        f"{key}_published_source_urls",
        f"{key}_published_retrieved",
        f"{key}_published_sha256s",
    ]
    lines = [
        f"module Tides.Published.{pascal(key)}",
        "import Std.Datetime (Date, date)",
        f"export ({', '.join(names)})",
        HEADER,
        f"-- Source: {source.authority}, retrieved {retrieved(snaps).isoformat()}.",
    ]
    year_defs = []
    for year, group in itertools.groupby(published.holidays, key=lambda h: h.day.year):
        holidays = list(group)
        listing = "; ".join(f"{h.day:%m-%d} {comment_text(h.name)}" for h in holidays)
        lines.append(f"-- {year}: {listing}")
        closes = [c for c in published.early_closes if c.day.year == year]
        if closes:
            early = "; ".join(f"{c.day:%m-%d} {comment_text(c.detail)}" for c in closes)
            lines.append(f"-- {year} early closes, which are business days: {early}")
        dates = ", ".join(date_literal(h.day) for h in holidays)
        lines.append(f"def {key}_{year}() -> List[Date] = [{dates}]")
        year_defs.append(f"{key}_{year}()")
    urls = ", ".join(string_literal(s.url) for s in ordered)
    digests = ", ".join(string_literal(s.sha256) for s in ordered)
    lines += [
        f"def {key}_published_holidays() -> List[Date] = flatten([{', '.join(year_defs)}])",
        f"def {key}_published_from() -> Date = {date_literal(published.valid_from)}",
        f"def {key}_published_until() -> Date = {date_literal(published.valid_until)}",
        f"def {key}_published_source() -> string = {string_literal(source.authority)}",
        f"def {key}_published_source_urls() -> List[string] = [{urls}]",
        f"def {key}_published_retrieved() -> Date = {date_literal(retrieved(snaps))}",
        f"def {key}_published_sha256s() -> List[string] = [{digests}]",
    ]
    return "\n".join(lines) + "\n"


def parsed_listing(source: Source, snaps: dict[str, Snapshot], published: Published) -> str:
    """Every dated entry the parse produced, one per line, so a regeneration that
    adds, removes or reclassifies a date shows as a line in review."""
    lines = [
        f"# {source.key}: {source.authority}",
        f"# horizon {published.valid_from.isoformat()}..{published.valid_until.isoformat()}",
    ]
    for part in source.parts:
        snap = snaps[part.name]
        lines.append(f"# {part.name}: {snap.url} retrieved {snap.retrieved.isoformat()} sha256 {snap.sha256}")
    entries = [(h.day, "holiday", h.name) for h in published.holidays]
    entries += [(e.day, "excluded", f"{e.name} ({e.reason})") for e in published.exclusions]
    entries += [(c.day, "early-close", f"{c.name} ({c.detail})") for c in published.early_closes]
    for day, kind, text in sorted(entries):
        lines.append(f"{day.isoformat()}\t{kind}\t{comment_text(text)}")
    return "\n".join(lines) + "\n"


def provenance_module(version: str) -> str:
    lines = [
        "module Tides.Provenance",
        "export (tides_version)",
        HEADER,
        "-- The package version: the newest retrieval date as year.MMDD, then a release counter.",
        f"def tides_version() -> string = {string_literal(version)}",
    ]
    return "\n".join(lines) + "\n"
