module BedHolidays.Published.EnglandAndWales
import Std.Datetime (Date, date)
export (england_and_wales_published_holidays, england_and_wales_published_from, england_and_wales_published_until, england_and_wales_published_source, england_and_wales_published_source_url, england_and_wales_published_retrieved, england_and_wales_published_sha256)
-- Generated by the bed-holidays sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- Source: UK Government Digital Service, gov.uk bank holidays, https://www.gov.uk/bank-holidays.json, retrieved 2026-10-05.
-- 2019: 01-01 New Year’s Day; 04-19 Good Friday; 04-22 Easter Monday; 05-06 Early May bank holiday; 05-27 Spring bank holiday; 08-26 Summer bank holiday; 12-25 Christmas Day; 12-26 Boxing Day
def england_and_wales_2019() -> List[Date] = [date(2019i64, 1i64, 1i64), date(2019i64, 4i64, 19i64), date(2019i64, 4i64, 22i64), date(2019i64, 5i64, 6i64), date(2019i64, 5i64, 27i64), date(2019i64, 8i64, 26i64), date(2019i64, 12i64, 25i64), date(2019i64, 12i64, 26i64)]
-- 2020: 01-01 New Year’s Day; 04-10 Good Friday; 04-13 Easter Monday; 05-08 Early May bank holiday (VE day); 05-25 Spring bank holiday; 08-31 Summer bank holiday; 12-25 Christmas Day; 12-28 Boxing Day
def england_and_wales_2020() -> List[Date] = [date(2020i64, 1i64, 1i64), date(2020i64, 4i64, 10i64), date(2020i64, 4i64, 13i64), date(2020i64, 5i64, 8i64), date(2020i64, 5i64, 25i64), date(2020i64, 8i64, 31i64), date(2020i64, 12i64, 25i64), date(2020i64, 12i64, 28i64)]
-- 2021: 01-01 New Year’s Day; 04-02 Good Friday; 04-05 Easter Monday; 05-03 Early May bank holiday; 05-31 Spring bank holiday; 08-30 Summer bank holiday; 12-27 Christmas Day; 12-28 Boxing Day
def england_and_wales_2021() -> List[Date] = [date(2021i64, 1i64, 1i64), date(2021i64, 4i64, 2i64), date(2021i64, 4i64, 5i64), date(2021i64, 5i64, 3i64), date(2021i64, 5i64, 31i64), date(2021i64, 8i64, 30i64), date(2021i64, 12i64, 27i64), date(2021i64, 12i64, 28i64)]
-- 2022: 01-03 New Year’s Day; 04-15 Good Friday; 04-18 Easter Monday; 05-02 Early May bank holiday; 06-02 Spring bank holiday; 06-03 Platinum Jubilee bank holiday; 08-29 Summer bank holiday; 09-19 Bank Holiday for the State Funeral of Queen Elizabeth II; 12-26 Boxing Day; 12-27 Christmas Day
def england_and_wales_2022() -> List[Date] = [date(2022i64, 1i64, 3i64), date(2022i64, 4i64, 15i64), date(2022i64, 4i64, 18i64), date(2022i64, 5i64, 2i64), date(2022i64, 6i64, 2i64), date(2022i64, 6i64, 3i64), date(2022i64, 8i64, 29i64), date(2022i64, 9i64, 19i64), date(2022i64, 12i64, 26i64), date(2022i64, 12i64, 27i64)]
-- 2023: 01-02 New Year’s Day; 04-07 Good Friday; 04-10 Easter Monday; 05-01 Early May bank holiday; 05-08 Bank holiday for the coronation of King Charles III; 05-29 Spring bank holiday; 08-28 Summer bank holiday; 12-25 Christmas Day; 12-26 Boxing Day
def england_and_wales_2023() -> List[Date] = [date(2023i64, 1i64, 2i64), date(2023i64, 4i64, 7i64), date(2023i64, 4i64, 10i64), date(2023i64, 5i64, 1i64), date(2023i64, 5i64, 8i64), date(2023i64, 5i64, 29i64), date(2023i64, 8i64, 28i64), date(2023i64, 12i64, 25i64), date(2023i64, 12i64, 26i64)]
-- 2024: 01-01 New Year’s Day; 03-29 Good Friday; 04-01 Easter Monday; 05-06 Early May bank holiday; 05-27 Spring bank holiday; 08-26 Summer bank holiday; 12-25 Christmas Day; 12-26 Boxing Day
def england_and_wales_2024() -> List[Date] = [date(2024i64, 1i64, 1i64), date(2024i64, 3i64, 29i64), date(2024i64, 4i64, 1i64), date(2024i64, 5i64, 6i64), date(2024i64, 5i64, 27i64), date(2024i64, 8i64, 26i64), date(2024i64, 12i64, 25i64), date(2024i64, 12i64, 26i64)]
-- 2025: 01-01 New Year’s Day; 04-18 Good Friday; 04-21 Easter Monday; 05-05 Early May bank holiday; 05-26 Spring bank holiday; 08-25 Summer bank holiday; 12-25 Christmas Day; 12-26 Boxing Day
def england_and_wales_2025() -> List[Date] = [date(2025i64, 1i64, 1i64), date(2025i64, 4i64, 18i64), date(2025i64, 4i64, 21i64), date(2025i64, 5i64, 5i64), date(2025i64, 5i64, 26i64), date(2025i64, 8i64, 25i64), date(2025i64, 12i64, 25i64), date(2025i64, 12i64, 26i64)]
-- 2026: 01-01 New Year’s Day; 04-03 Good Friday; 04-06 Easter Monday; 05-04 Early May bank holiday; 05-25 Spring bank holiday; 08-31 Summer bank holiday; 12-25 Christmas Day; 12-28 Boxing Day
def england_and_wales_2026() -> List[Date] = [date(2026i64, 1i64, 1i64), date(2026i64, 4i64, 3i64), date(2026i64, 4i64, 6i64), date(2026i64, 5i64, 4i64), date(2026i64, 5i64, 25i64), date(2026i64, 8i64, 31i64), date(2026i64, 12i64, 25i64), date(2026i64, 12i64, 28i64)]
-- 2027: 01-01 New Year’s Day; 03-26 Good Friday; 03-29 Easter Monday; 05-03 Early May bank holiday; 05-31 Spring bank holiday; 08-30 Summer bank holiday; 12-27 Christmas Day; 12-28 Boxing Day
def england_and_wales_2027() -> List[Date] = [date(2027i64, 1i64, 1i64), date(2027i64, 3i64, 26i64), date(2027i64, 3i64, 29i64), date(2027i64, 5i64, 3i64), date(2027i64, 5i64, 31i64), date(2027i64, 8i64, 30i64), date(2027i64, 12i64, 27i64), date(2027i64, 12i64, 28i64)]
-- 2028: 01-03 New Year’s Day; 04-14 Good Friday; 04-17 Easter Monday; 05-01 Early May bank holiday; 05-29 Spring bank holiday; 08-28 Summer bank holiday; 12-25 Christmas Day; 12-26 Boxing Day
def england_and_wales_2028() -> List[Date] = [date(2028i64, 1i64, 3i64), date(2028i64, 4i64, 14i64), date(2028i64, 4i64, 17i64), date(2028i64, 5i64, 1i64), date(2028i64, 5i64, 29i64), date(2028i64, 8i64, 28i64), date(2028i64, 12i64, 25i64), date(2028i64, 12i64, 26i64)]
def england_and_wales_published_holidays() -> List[Date] = flatten([england_and_wales_2019(), england_and_wales_2020(), england_and_wales_2021(), england_and_wales_2022(), england_and_wales_2023(), england_and_wales_2024(), england_and_wales_2025(), england_and_wales_2026(), england_and_wales_2027(), england_and_wales_2028()])
def england_and_wales_published_from() -> Date = date(2019i64, 1i64, 1i64)
def england_and_wales_published_until() -> Date = date(2028i64, 12i64, 31i64)
def england_and_wales_published_source() -> string = "UK Government Digital Service, gov.uk bank holidays"
def england_and_wales_published_source_url() -> string = "https://www.gov.uk/bank-holidays.json"
def england_and_wales_published_retrieved() -> Date = date(2026i64, 10i64, 5i64)
def england_and_wales_published_sha256() -> string = "538b3482c28b85ecd2db606a0d5ae6ad17248900b6498700ce0a48d26a3ecde6"
