module Tides.Published.NewSouthWales
import Std.Datetime (Date, date)
export (new_south_wales_published_holidays, new_south_wales_published_from, new_south_wales_published_until, new_south_wales_published_source, new_south_wales_published_source_urls, new_south_wales_published_retrieved, new_south_wales_published_sha256s)
-- Generated by the tides sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- Source: NSW Government, public holidays (Public Holidays Act 2010), retrieved 2026-10-05.
-- 2026: 01-01 New Year's Day; 01-26 Australia Day; 04-03 Good Friday; 04-04 Easter Saturday; 04-05 Easter Sunday; 04-06 Easter Monday; 04-25 Anzac Day; 04-27 Additional Day; 06-08 King's Birthday; 10-05 Labour Day; 12-25 Christmas Day; 12-26 Boxing Day; 12-28 Additional Day
def new_south_wales_2026() -> List[Date] = [date(2026i64, 1i64, 1i64), date(2026i64, 1i64, 26i64), date(2026i64, 4i64, 3i64), date(2026i64, 4i64, 4i64), date(2026i64, 4i64, 5i64), date(2026i64, 4i64, 6i64), date(2026i64, 4i64, 25i64), date(2026i64, 4i64, 27i64), date(2026i64, 6i64, 8i64), date(2026i64, 10i64, 5i64), date(2026i64, 12i64, 25i64), date(2026i64, 12i64, 26i64), date(2026i64, 12i64, 28i64)]
-- 2027: 01-01 New Year's Day; 01-26 Australia Day; 03-26 Good Friday; 03-27 Easter Saturday; 03-28 Easter Sunday; 03-29 Easter Monday; 04-25 Anzac Day; 04-26 Additional Day; 06-14 King's Birthday; 10-04 Labour Day; 12-25 Christmas Day; 12-26 Boxing Day; 12-27 Additional Day; 12-28 Additional Day
def new_south_wales_2027() -> List[Date] = [date(2027i64, 1i64, 1i64), date(2027i64, 1i64, 26i64), date(2027i64, 3i64, 26i64), date(2027i64, 3i64, 27i64), date(2027i64, 3i64, 28i64), date(2027i64, 3i64, 29i64), date(2027i64, 4i64, 25i64), date(2027i64, 4i64, 26i64), date(2027i64, 6i64, 14i64), date(2027i64, 10i64, 4i64), date(2027i64, 12i64, 25i64), date(2027i64, 12i64, 26i64), date(2027i64, 12i64, 27i64), date(2027i64, 12i64, 28i64)]
def new_south_wales_published_holidays() -> List[Date] = flatten([new_south_wales_2026(), new_south_wales_2027()])
def new_south_wales_published_from() -> Date = date(2026i64, 1i64, 1i64)
def new_south_wales_published_until() -> Date = date(2027i64, 12i64, 31i64)
def new_south_wales_published_source() -> string = "NSW Government, public holidays (Public Holidays Act 2010)"
def new_south_wales_published_source_urls() -> List[string] = ["https://www.nsw.gov.au/about-nsw/public-holidays"]
def new_south_wales_published_retrieved() -> Date = date(2026i64, 10i64, 5i64)
def new_south_wales_published_sha256s() -> List[string] = ["f4332a5a07f05e96e0531b137621f31593101e110a137ca720c4e8a813cbb9c1"]
