module Shoreleave.Published.Nyse
import Std.Datetime (Date, date)
export (nyse_published_holidays, nyse_published_from, nyse_published_until, nyse_published_source, nyse_published_source_urls, nyse_published_retrieved, nyse_published_sha256s)
-- Generated by the shoreleave sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- Source: New York Stock Exchange, holidays and trading hours, retrieved 2026-10-05.
-- 2026: 01-01 New Year’s Day; 01-19 Martin Luther King, Jr. Day; 02-16 Washington's Birthday; 04-03 Good Friday; 05-25 Memorial Day; 06-19 Juneteenth National Independence Day; 07-03 Independence Day; 09-07 Labor Day; 11-26 Thanksgiving Day; 12-25 Christmas Day
-- 2026 early closes, which are business days: 11-27 closes at 1:00 p.m. (1:15 p.m. for eligible options) Eastern Time; 12-24 closes at 1:00 p.m. (1:15 p.m. for eligible options) Eastern Time
def nyse_2026() -> List[Date] = [date(2026i64, 1i64, 1i64), date(2026i64, 1i64, 19i64), date(2026i64, 2i64, 16i64), date(2026i64, 4i64, 3i64), date(2026i64, 5i64, 25i64), date(2026i64, 6i64, 19i64), date(2026i64, 7i64, 3i64), date(2026i64, 9i64, 7i64), date(2026i64, 11i64, 26i64), date(2026i64, 12i64, 25i64)]
-- 2027: 01-01 New Year’s Day; 01-18 Martin Luther King, Jr. Day; 02-15 Washington's Birthday; 03-26 Good Friday; 05-31 Memorial Day; 06-18 Juneteenth National Independence Day; 07-05 Independence Day; 09-06 Labor Day; 11-25 Thanksgiving Day; 12-24 Christmas Day
-- 2027 early closes, which are business days: 11-26 closes at 1:00 p.m. (1:15 p.m. for eligible options) Eastern Time
def nyse_2027() -> List[Date] = [date(2027i64, 1i64, 1i64), date(2027i64, 1i64, 18i64), date(2027i64, 2i64, 15i64), date(2027i64, 3i64, 26i64), date(2027i64, 5i64, 31i64), date(2027i64, 6i64, 18i64), date(2027i64, 7i64, 5i64), date(2027i64, 9i64, 6i64), date(2027i64, 11i64, 25i64), date(2027i64, 12i64, 24i64)]
-- 2028: 01-17 Martin Luther King, Jr. Day; 02-21 Washington's Birthday; 04-14 Good Friday; 05-29 Memorial Day; 06-19 Juneteenth National Independence Day; 07-04 Independence Day; 09-04 Labor Day; 11-23 Thanksgiving Day; 12-25 Christmas Day
-- 2028 early closes, which are business days: 07-03 closes at 1:00 p.m. (1:15 p.m. for eligible options) Eastern Time; 11-24 closes at 1:00 p.m. (1:15 p.m. for eligible options) Eastern Time
def nyse_2028() -> List[Date] = [date(2028i64, 1i64, 17i64), date(2028i64, 2i64, 21i64), date(2028i64, 4i64, 14i64), date(2028i64, 5i64, 29i64), date(2028i64, 6i64, 19i64), date(2028i64, 7i64, 4i64), date(2028i64, 9i64, 4i64), date(2028i64, 11i64, 23i64), date(2028i64, 12i64, 25i64)]
def nyse_published_holidays() -> List[Date] = flatten([nyse_2026(), nyse_2027(), nyse_2028()])
def nyse_published_from() -> Date = date(2026i64, 1i64, 1i64)
def nyse_published_until() -> Date = date(2028i64, 12i64, 31i64)
def nyse_published_source() -> string = "New York Stock Exchange, holidays and trading hours"
def nyse_published_source_urls() -> List[string] = ["https://www.nyse.com/markets/hours-calendars"]
def nyse_published_retrieved() -> Date = date(2026i64, 10i64, 5i64)
def nyse_published_sha256s() -> List[string] = ["79602f7be5a8f1d39c2b1cac4dd02c4c07f18cf9f92d70602834069154719bad"]
