module Tides.Published.Sifma
import Std.Datetime (Date, date)
export (sifma_published_holidays, sifma_published_from, sifma_published_until, sifma_published_source, sifma_published_source_urls, sifma_published_retrieved, sifma_published_sha256s)
-- Generated by the tides sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- Source: SIFMA, US holiday recommendations (fixed income), retrieved 2026-10-05.
-- 2026: 01-01 New Year’s Day; 01-19 Martin Luther King Day; 02-16 Presidents Day; 05-25 Memorial Day; 06-19 Juneteenth; 07-03 U.S. Independence Day (observed); 09-07 Labor Day; 10-12 Columbus Day; 11-11 Veterans Day; 11-26 Thanksgiving Day; 12-25 Christmas Day
-- 2026 early closes, which are business days: 04-03 closes at 12:00 p.m. Eastern Time; 05-22 closes at 2:00 p.m. Eastern Time; 07-02 closes at 2:00 p.m. Eastern Time; 11-27 closes at 2:00 p.m. Eastern Time; 12-24 closes at 2:00 p.m. Eastern Time; 12-31 closes at 2:00 p.m. Eastern Time
def sifma_2026() -> List[Date] = [date(2026i64, 1i64, 1i64), date(2026i64, 1i64, 19i64), date(2026i64, 2i64, 16i64), date(2026i64, 5i64, 25i64), date(2026i64, 6i64, 19i64), date(2026i64, 7i64, 3i64), date(2026i64, 9i64, 7i64), date(2026i64, 10i64, 12i64), date(2026i64, 11i64, 11i64), date(2026i64, 11i64, 26i64), date(2026i64, 12i64, 25i64)]
-- 2027: 01-01 New Year’s Day; 01-18 Martin Luther King Day; 02-15 Presidents Day; 03-26 Good Friday; 05-31 Memorial Day; 06-18 Juneteenth; 07-05 U.S. Independence Day; 09-06 Labor Day; 10-11 Columbus Day; 11-11 Veterans Day; 11-25 Thanksgiving Day; 12-24 Christmas Day
-- 2027 early closes, which are business days: 03-25 closes at 2:00 p.m. Eastern Time; 05-28 closes at 2:00 p.m. Eastern Time; 07-02 closes at 2:00 p.m. Eastern Time; 11-26 closes at 2:00 p.m. Eastern Time; 12-23 closes at 2:00 p.m. Eastern Time; 12-31 closes at 2:00 p.m. Eastern Time
def sifma_2027() -> List[Date] = [date(2027i64, 1i64, 1i64), date(2027i64, 1i64, 18i64), date(2027i64, 2i64, 15i64), date(2027i64, 3i64, 26i64), date(2027i64, 5i64, 31i64), date(2027i64, 6i64, 18i64), date(2027i64, 7i64, 5i64), date(2027i64, 9i64, 6i64), date(2027i64, 10i64, 11i64), date(2027i64, 11i64, 11i64), date(2027i64, 11i64, 25i64), date(2027i64, 12i64, 24i64)]
def sifma_published_holidays() -> List[Date] = flatten([sifma_2026(), sifma_2027()])
def sifma_published_from() -> Date = date(2026i64, 1i64, 1i64)
def sifma_published_until() -> Date = date(2027i64, 12i64, 31i64)
def sifma_published_source() -> string = "SIFMA, US holiday recommendations (fixed income)"
def sifma_published_source_urls() -> List[string] = ["https://www.sifma.org/resources/general/holiday-schedule/"]
def sifma_published_retrieved() -> Date = date(2026i64, 10i64, 5i64)
def sifma_published_sha256s() -> List[string] = ["67b51cff36d8049e52a02769403f9b4c36202e1420bb8cc56b0fe5413088921b"]
