module BedHolidays.Published.Target
import Std.Datetime (Date, date)
export (target_published_holidays, target_published_from, target_published_until, target_published_source, target_published_source_url, target_published_retrieved, target_published_sha256)
-- Generated by the bed-holidays sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- Source: European Central Bank, TARGET closing days, https://www.ecb.europa.eu/ecb/contacts/working-hours/html/index.en.html, retrieved 2026-10-05.
-- 2026: 01-01 New Year's Day; 04-03 Good Friday; 04-06 Easter Monday; 05-01 Labour Day; 12-25 Christmas Day; 12-26 Christmas Holiday
def target_2026() -> List[Date] = [date(2026i64, 1i64, 1i64), date(2026i64, 4i64, 3i64), date(2026i64, 4i64, 6i64), date(2026i64, 5i64, 1i64), date(2026i64, 12i64, 25i64), date(2026i64, 12i64, 26i64)]
-- 2027: 01-01 New Year's Day; 03-26 Good Friday; 03-29 Easter Monday; 05-01 Labour Day; 12-25 Christmas Day; 12-26 Christmas Holiday
def target_2027() -> List[Date] = [date(2027i64, 1i64, 1i64), date(2027i64, 3i64, 26i64), date(2027i64, 3i64, 29i64), date(2027i64, 5i64, 1i64), date(2027i64, 12i64, 25i64), date(2027i64, 12i64, 26i64)]
-- 2028: 01-01 New Year's Day; 04-14 Good Friday; 04-17 Easter Monday; 05-01 Labour Day; 12-25 Christmas Day; 12-26 Christmas Holiday
def target_2028() -> List[Date] = [date(2028i64, 1i64, 1i64), date(2028i64, 4i64, 14i64), date(2028i64, 4i64, 17i64), date(2028i64, 5i64, 1i64), date(2028i64, 12i64, 25i64), date(2028i64, 12i64, 26i64)]
def target_published_holidays() -> List[Date] = flatten([target_2026(), target_2027(), target_2028()])
def target_published_from() -> Date = date(2026i64, 1i64, 1i64)
def target_published_until() -> Date = date(2028i64, 12i64, 31i64)
def target_published_source() -> string = "European Central Bank, TARGET closing days"
def target_published_source_url() -> string = "https://www.ecb.europa.eu/ecb/contacts/working-hours/html/index.en.html"
def target_published_retrieved() -> Date = date(2026i64, 10i64, 5i64)
def target_published_sha256() -> string = "ee7ee2d44a95ca77b1ab742a8b55f75748034498e460826fad460affbbf15be3"
