"""Emit the generated Chelis modules: one data module per calendar and the
package's provenance module. Output is already in `chelis fmt` canonical form."""

from __future__ import annotations

import datetime
import itertools
import re

from bed_holidays_sync.model import Published, Source
from bed_holidays_sync.snapshot import Snapshot

HEADER = "-- Generated by the bed-holidays sync generator from its pinned upstream snapshot. Do not edit; regenerate."


def pascal(key: str) -> str:
    return "".join(part.capitalize() for part in key.split("_"))


def string_literal(text: str) -> str:
    if not re.fullmatch(r"[ -~]*", text):
        raise ValueError(f"non-ASCII or control character in {text!r}")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def date_literal(day: datetime.date) -> str:
    return f"date({day.year}i64, {day.month}i64, {day.day}i64)"


def comment_text(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def published_module(source: Source, snapshot: Snapshot, published: Published) -> str:
    key = source.key
    names = [
        f"{key}_published_holidays",
        f"{key}_published_from",
        f"{key}_published_until",
        f"{key}_published_source",
        f"{key}_published_source_url",
        f"{key}_published_retrieved",
        f"{key}_published_sha256",
    ]
    lines = [
        f"module BedHolidays.Published.{pascal(key)}",
        "import Std.Datetime (Date, date)",
        f"export ({', '.join(names)})",
        HEADER,
        f"-- Source: {source.authority}, {source.url}, retrieved {snapshot.retrieved.isoformat()}.",
    ]
    year_defs = []
    by_year = itertools.groupby(published.holidays, key=lambda h: h.day.year)
    for year, group in by_year:
        holidays = list(group)
        listing = "; ".join(f"{h.day:%m-%d} {comment_text(h.name)}" for h in holidays)
        lines.append(f"-- {year}: {listing}")
        dates = ", ".join(date_literal(h.day) for h in holidays)
        lines.append(f"def {key}_{year}() -> List[Date] = [{dates}]")
        year_defs.append(f"{key}_{year}()")
    lines += [
        f"def {key}_published_holidays() -> List[Date] = flatten([{', '.join(year_defs)}])",
        f"def {key}_published_from() -> Date = {date_literal(published.valid_from)}",
        f"def {key}_published_until() -> Date = {date_literal(published.valid_until)}",
        f"def {key}_published_source() -> string = {string_literal(source.authority)}",
        f"def {key}_published_source_url() -> string = {string_literal(source.url)}",
        f"def {key}_published_retrieved() -> Date = {date_literal(snapshot.retrieved)}",
        f"def {key}_published_sha256() -> string = {string_literal(snapshot.sha256)}",
    ]
    return "\n".join(lines) + "\n"


def provenance_module(version: str) -> str:
    lines = [
        "module BedHolidays.Provenance",
        "export (holidays_version)",
        HEADER,
        "-- The package version: the newest retrieval date as year.MMDD, then a release counter.",
        f"def holidays_version() -> string = {string_literal(version)}",
    ]
    return "\n".join(lines) + "\n"
