module BedHolidays.Provenance
export (holidays_version)
-- Generated by the bed-holidays sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- The package version: the newest retrieval date as year.MMDD, then a release counter.
def holidays_version() -> string = "2026.1005.0"
