module Shoreleave.Provenance
export (shoreleave_version)
-- Generated by the shoreleave sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- The package version: the newest retrieval date as year.MMDD, then a release counter.
def shoreleave_version() -> string = "2026.1005.0"
