module Tides.Provenance
export (tides_version)
-- Generated by the tides sync generator from its pinned upstream snapshot. Do not edit; regenerate.
-- The package version: the newest retrieval date as year.MMDD, then a release counter.
def tides_version() -> string = "2026.1005.0"
